[package]
name = "arm"
version = "0.1.0"
authors = ["Chris Pearce <chris@pearce.org.nz>"]

[dependencies]
rayon = "0.8.2"
itertools = "0.6.1"
argparse = "*"
metrohash = "1.0.5"

[profile.release]
debug = true
